[package]
name = "first_unit_test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "first_unit_test"
path = "src/first_unit_test.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
