[package]
name = "variables"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "variables"
path = "src/variables.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
