[package]
name = "word-counter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "word_counter"
path = "src/word_counter.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
